//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL6968.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_PHONG
    {
        public string SoHoaDon { get; set; }
        public string MaPhong { get; set; }
        public string MaNhanVien { get; set; }
        public string MaKhachHang { get; set; }
        public System.DateTime ThoiGianDat { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual HOA_DON HOA_DON { get; set; }
    }
}
