//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL6968.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string SoHoaDon { get; set; }
        public string MaNhanVienXuatHD { get; set; }
        public string MaKhachHang { get; set; }
        public string MaPhong { get; set; }
        public System.DateTime ThoiGianDat { get; set; }
        public Nullable<System.DateTime> ThoiGianTra { get; set; }
        public Nullable<decimal> TongGiaPhong { get; set; }
        public Nullable<decimal> TongGiaDichVu { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> GiaPhong1Ngay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
