//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL6968.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public string MaPhong { get; set; }
        public string MaLoaiPhong { get; set; }
        public string GhiChu { get; set; }
        public string TenPhong { get; set; }
        public Nullable<short> MaTinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual LOAI_PHONG LOAI_PHONG { get; set; }
        public virtual TINH_TRANG TINH_TRANG { get; set; }
    }
}
