//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO
    {
        public string MaBaoCao { get; set; }
        public string TenBaoCao { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<decimal> DoanhThuPhong { get; set; }
        public Nullable<decimal> DoanhThuDichVu { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
