//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOI_PHONG
    {
        public string MaPhongCu { get; set; }
        public string SoHoaDon { get; set; }
        public string MaPhongMoi { get; set; }
        public string MaNhanVien { get; set; }
    
        public virtual DAT_PHONG DAT_PHONG { get; set; }
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
