//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.DAT_PHONG = new HashSet<DAT_PHONG>();
            this.DOI_PHONG = new HashSet<DOI_PHONG>();
        }
    
        public string SoHoaDon { get; set; }
        public string MaNhanVienXuatHD { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public System.DateTime ThoiGianXuatHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PHONG> DAT_PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOI_PHONG> DOI_PHONG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
